config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  resources :messages
  resources :incubators
  resources :stages
  resources :locations
  resources :posts
  resources :start_ups

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end

  devise_scope :user do
      root to: "devise/sessions#new"
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/start_up.rb
class StartUp < ActiveRecord::Base
  validates :name, presence: true
  validates :short_description, presence: true
  validates :long_description, presence: true
  validates :image, presence: true
  validates :video, presence: true
  validates :stage_id, presence: true
  validates :incubator_id, presence: true
  validates :location_id, presence: true

<<<<<<< HEAD
  mount_uploader :image, StartUpsImageUploader

end
=======
end
>>>>>>> a43a0fb97eb2bdf5e97926e2186b310cd461c914

app/controllers/start_ups_controller.rb
class StartUpsController < ApplicationController
  before_action :set_start_up, only: [:show, :edit, :update, :destroy]

  # GET /start_ups
  # GET /start_ups.json
  def index
    @start_ups = StartUp.all
  end

  # GET /start_ups/1
  # GET /start_ups/1.json
  def show
    if @start_up.stage_id == 5
      @mobile_graphic_url = "http://res.cloudinary.com/small-change/image/upload/v1462195241/idea_mobile_eil6uj.png"
      @graphic_large_url = "http://res.cloudinary.com/small-change/image/upload/v1461927711/idea_s2xbdp.png"
    elsif @start_up.stage_id == 6
      @mobile_graphic_url = "http://res.cloudinary.com/small-change/image/upload/v1462195255/mvp_mobile_ppss9q.png"
      @graphic_large_url = "http://res.cloudinary.com/small-change/image/upload/v1461927729/mvp_ippmsx.png"
    elsif @start_up.stage_id == 7
      @mobile_graphic_url = "http://res.cloudinary.com/small-change/image/upload/v1462195266/pm_fit_mobile_vgcmqu.png"
      @graphic_large_url = "http://res.cloudinary.com/small-change/image/upload/v1461927741/pm_fit_os4fuo.png"
    elsif @start_up.stage_id === 8
      @mobile_graphic_url = "http://res.cloudinary.com/small-change/image/upload/v1462195277/growth_mobile_hrmqcz.png"
      @graphic_large_url = "http://res.cloudinary.com/small-change/image/upload/v1461927755/growth_vycutm.png"
    end
  end

  # GET /start_ups/new
  def new
    @start_up = StartUp.new
  end

  # GET /start_ups/1/edit
  def edit
  end

  # POST /start_ups
  # POST /start_ups.json
  def create
    @start_up = StartUp.new(start_up_params)

    respond_to do |format|
      if @start_up.save
        format.html { redirect_to @start_up, notice: 'Start up was successfully created.' }
        format.json { render :show, status: :created, location: @start_up }
      else
        format.html { render :new }
        format.json { render json: @start_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /start_ups/1
  # PATCH/PUT /start_ups/1.json
  def update
    respond_to do |format|
      if @start_up.update(start_up_params)
        format.html { redirect_to @start_up, notice: 'Start up was successfully updated.' }
        format.json { render :show, status: :ok, location: @start_up }
      else
        format.html { render :edit }
        format.json { render json: @start_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /start_ups/1
  # DELETE /start_ups/1.json
  def destroy
    @start_up.destroy
    respond_to do |format|
      format.html { redirect_to start_ups_url, notice: 'Start up was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_start_up
      @start_up = StartUp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def start_up_params
      params.require(:start_up).permit(:name, :short_description, :long_description, :image, :video, :stage_id, :incubator_id, :location_id, :user_id)
    end
end

app/helpers/start_ups_helper.rb
module StartUpsHelper
end

app/views/start_ups/_form.html.erb
<div class='container'>
  <%= simple_form_for(@start_up) do |f| %>
    <%= f.error_notification %>
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="form-inputs">
        <%= f.input :name, :required => true, class: "startup-form", placeholder: "name of start up", label: false%>
        <%= f.input :short_description, :required => true, class: "startup-form", placeholder: "short description (max 50 characters)", label: false%>
        <%= f.input :long_description, :required => true, class: "startup-form", placeholder: "long description (max 600 characters)", label: false%>
<<<<<<< HEAD
        <div class="carrierwave-field">
        <%= f.input :image, :required => true, class: "startup-form", placeholder: "logo url", label: false, width: "100%" %>
        </div>
        <%= f.input :video, :required => false, class: "startup-form", placeholder: "video url. stuck? do a short YouTube video of your pitch", label: false%>
        <p class=" dont-read pull-right"> *people don't read. the description is mainly for keen beans... </p>

=======
        <%= f.input :image, :required => true, class: "startup-form", placeholder: "logo url", label: false%>
        <%= f.input :video, :required => true, class: "startup-form", placeholder: "video url. stuck? do a short YouTube video of your pitch", label: false%>
        <p class=" dont-read pull-right"> *people don't read. the description is mainly for keen beans... </p>
    
>>>>>>> a43a0fb97eb2bdf5e97926e2186b310cd461c914
          <%= f.input :stage_id, :collection => Stage.all.pluck(:stage_name), class: "startup-form", placeholder: "stage", label: 'Stage'%>
          <%= f.input :incubator_id, :collection => Incubator.all.pluck(:name), class: "startup-form", placeholder: "stage", label: 'Incubator'%>
          <%= f.input :location_id, :collection => Location.all.pluck(:city), class: "startup-form", placeholder: "stage", label: 'City'%>
      </div>
      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-blue-start-up", value: "Create" %>
      </div>
    </div>
  <% end %>
</div>
<<<<<<< HEAD
=======





>>>>>>> a43a0fb97eb2bdf5e97926e2186b310cd461c914

app/views/start_ups/edit.html.erb
<h1>Editing Start Up</h1>

<%= render 'form' %>

<%= link_to 'Show', @start_up %> |
<%= link_to 'Back', start_ups_path %>

app/views/start_ups/index.html.erb
<div class="incubator-heading">
  <h1 class="app-heading">Listing Start Ups</h1>
</div>
<table class="table table-hover table-bg">
  <thead>
    <tr>
      <th>Name</th>
      <th>Short Description</th>
      <th>Long Description</th>
      <th>Image</th>
      <th>Video</th>
      <th>Stage</th>
      <th>Incbator</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @start_ups.each do |start_up| %>
      <tr>
      <td><%= start_up.name %></td>
      <td><%= start_up.short_description %></td>
      <td><%= start_up.long_description %></td>
      <td><%= start_up.image %></td>
      <td><%= start_up.video %></td>
      <td><%= start_up.stage_id %></td>
      <td><%= start_up.incubator_id %></td>
      <td><%= start_up.location_id %></td>
      <td><%= link_to 'Show', start_up %></td>
      <td><%= link_to 'Edit', edit_start_up_path(start_up) %></td>
      <td><%= link_to 'Destroy', start_up, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Start Up', new_start_up_path, class: 'btn btn-blue' %>

app/views/start_ups/new.html.erb
<div class="incubator-heading">
  <h1 class="app-heading">New Start Up</h1>
</div>
<%= render 'form' %>

app/views/start_ups/show.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <div class="title-panel">
      <div class="col-xs-4 col-sm-2">
        <img src="https://www.brownbagmarketing.com/wp-content/uploads/2014/07/Airbnb-new-logo-1-1024x863.jpg" class="company-logo">
      </div>
      <div class="col-xs-8 col-sm-8">
        <h2 class="start-up-name"><%= @start_up.name %></h2> 
        <p class="short-des"><%= @start_up.short_description %></p>
        <div class="mobile-envelope">
          <i class="fa fa-envelope fa-2x visible-xs pull-right" aria-hidden="true"></i>
        </div>
      </div>
      <div class="hidden-xs">
        <div class="col-sm-2">
          <div class="contact-box">
            <i class="fa fa-envelope fa-3x" aria-hidden="true"></i>
            <p class="olive-branch"> extend the olive branch </p>
          </div>
        </div>
      </div>
    </div>
    <div class="hidden-xs">
      <img src="<%= @graphic_large_url %>" width="100%" class="stage-graphic">
    </div>
    <div class="visible-xs">
      <img src="<%= @mobile_graphic_url %>" width="100%" class="stage-graphic">
    </div>
    <div class="col-sm-7">
      <div class="video-panel">
      <iframe width="100%" src="https://www.youtube.com/embed/QweNsLesMrM" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="wish-panel">
      </div>
    </div>
    <div class="about-panel">
    </div>
  </div>
</div>