config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  resources :messages
  resources :incubators
  resources :stages
  resources :locations
  resources :posts
  resources :start_ups

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end

  devise_scope :user do
      root to: "devise/sessions#new"
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/stage.rb
class Stage < ActiveRecord::Base
  has_many :start_ups
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  # GET /stages
  # GET /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage, notice: 'Stage was successfully created.' }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to @stage, notice: 'Stage was successfully updated.' }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to stages_url, notice: 'Stage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      params.require(:stage).permit(:stage_name, :stage_description, :stage_icon)
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<div class='col-xs-12 col-sm-8 col-sm-2 col-md-6 col-md-offset-3'>
  <%= simple_form_for(@stage) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :stage_name, :required => true, class: "stage-form", placeholder: "name of stage", label: false%>
      <%= f.input :stage_description, :required => true, class: "stage-form", placeholder: "description of stage", label: false%>
      <%= f.input :stage_icon, :required => true, class: "stage-form", placeholder: "url of stage icon", label: false%>
    </div>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-blue" %>
      <%= link_to 'Back', stages_path, class: "btn btn-blue" %>
    </div>
  <% end %>
</div>

app/views/stages/edit.html.erb
<div class="incubator-heading">
  <h1 class="app-heading">Edit Stage</h1>
</div>
<%= render 'form' %>

app/views/stages/index.html.erb
<div class="incubator-heading">
  <h1 class="app-heading">Stages</h1>
</div>
<table class="table table-hover table-bg">
  <thead>
    <tr>
    <th>Stage name</th>
    <th>Stage description</th>
    <th>Stage icon</th>
    <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.stage_name %></td>
        <td><%= stage.stage_description %></td>
        <td><img src="<%= stage.stage_icon %>", class="stage_icon"></td>
        <td><%= link_to 'Show', stage, class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage), class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Stage', new_stage_path, class: 'btn btn-blue' %>

app/views/stages/new.html.erb
<div class="incubator-heading">
  <h1 class="app-heading">New Stage</h1>
</div>
<%= render 'form' %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>
<div class="incubator-heading">
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="stage-box">
      <h1 class="app-heading">Stage Name: <small class="white"><%= @stage.stage_name %></small></h1>
    </div>
  </div>
</div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="stage-box">
        <h1 class="app-heading">Stage description: <small class="white"><%= @stage.stage_description  %></small></h1>
      </div>
    </div>
  </div>
  <div class="stage-box">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
    <img src="<%= @stage.stage_icon %>" class="stage_icon" %>
  </div>
</div>
</div>
<center class="col-md-6 col-md-offset-3">
<%= link_to 'Edit', edit_stage_path(@stage), class: "btn btn-white" %>
<%= link_to 'Back', stages_path, class: "btn btn-white" %>
</center>