config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  resources :messages
  resources :incubators
  resources :stages
  resources :locations
  resources :posts
  resources :start_ups

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end

  devise_scope :user do
      root to: "devise/sessions#new"
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/incubator.rb
class Incubator < ActiveRecord::Base
end

app/controllers/incubators_controller.rb
class IncubatorsController < ApplicationController
  before_action :set_incubator, only: [:show, :edit, :update, :destroy]

  # GET /incubators
  # GET /incubators.json
  def index
    @incubators = Incubator.all
  end

  # GET /incubators/1
  # GET /incubators/1.json
  def show
  end

  # GET /incubators/new
  def new
    @incubator = Incubator.new
  end

  # GET /incubators/1/edit
  def edit
  end

  # POST /incubators
  # POST /incubators.json
  def create
    @incubator = Incubator.new(incubator_params)

    respond_to do |format|
      if @incubator.save
        format.html { redirect_to @incubator, notice: 'Incubator was successfully created.' }
        format.json { render :show, status: :created, location: @incubator }
      else
        format.html { render :new }
        format.json { render json: @incubator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incubators/1
  # PATCH/PUT /incubators/1.json
  def update
    respond_to do |format|
      if @incubator.update(incubator_params)
        format.html { redirect_to @incubator, notice: 'Incubator was successfully updated.' }
        format.json { render :show, status: :ok, location: @incubator }
      else
        format.html { render :edit }
        format.json { render json: @incubator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incubators/1
  # DELETE /incubators/1.json
  def destroy
    @incubator.destroy
    respond_to do |format|
      format.html { redirect_to incubators_url, notice: 'Incubator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incubator
      @incubator = Incubator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incubator_params
      params.require(:incubator).permit(:name)
    end
end

app/helpers/incubators_helper.rb
module IncubatorsHelper
end

app/views/incubators/_form.html.erb
<div class='col-xs-12 col-sm-8 col-sm-2 col-md-6 col-md-offset-3'>
  <%= simple_form_for(@incubator) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :name, :required => true, placeholder: "Name of Incubator", label: false%>
    </div>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-blue" %>
      <%= link_to 'Back', incubators_path, class: "btn btn-blue" %>
    </div>
  <% end %>
</div>

app/views/incubators/edit.html.erb
<div class="incubator-heading">
  <h1 class="app-heading">Edit Incubator</h1>
</div>
<%= render 'form' %>

app/views/incubators/index.html.erb
<div class="incubator-heading">
  <h1 class="app-heading">Listing Incubators</h1>
</div>
<table class="table table-hover table-bg">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @incubators.each do |incubator| %>
      <tr>
        <td><%= incubator.name %></td>
        <td><%= link_to 'Show', incubator, class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_incubator_path(incubator), class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', incubator, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Incubator', new_incubator_path, class: 'btn btn-blue' %>

app/views/incubators/new.html.erb
<div class="incubator-heading">
  <h1 class="app-heading">New Incubator</h1>
</div>
<%= render 'form' %>

app/views/incubators/show.html.erb
<p id="notice"><%= notice %></p>
<div class="incubator-heading">
  <h1 class="app-heading">Name <small class="white"><%= @incubator.name %></small></h1>
</div>
<center>
<%= link_to 'Edit', edit_incubator_path(@incubator), class: "btn btn-default" %>
<%= link_to 'Back', incubators_path, class: "btn btn-default" %>
</center>